version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: premier-erp-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: premier_erp
      POSTGRES_USER: erp_user
      POSTGRES_PASSWORD: erp_secure_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Premier ERP Application
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    container_name: premier-erp-app
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://erp_user:erp_secure_password@postgres:5432/premier_erp
      PORT: 5000
    ports:
      - "5000:5000"

volumes:
  postgres_data:
    driver: local