import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  isRTL: boolean;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation keys
const translations = {
  en: {
    // Navigation
    dashboard: 'Dashboard',
    products: 'Products',
    inventory: 'Inventory',
    expenses: 'Expenses',
    accounting: 'Accounting',
    suppliers: 'Suppliers',
    customers: 'Customers',
    createInvoice: 'Create Invoice',
    createQuotation: 'Create Quotation',
    invoiceHistory: 'Invoice History',
    quotationHistory: 'Quotation History',
    orderManagement: 'Order Management',
    ordersHistory: 'Orders History',
    label: 'Label',
    reports: 'Reports',
    procurement: 'Procurement',
    userManagement: 'User Management',
    systemPreferences: 'System Preferences',
    logout: 'Logout',
    
    // Common
    save: 'Save',
    cancel: 'Cancel',
    edit: 'Edit',
    delete: 'Delete',
    add: 'Add',
    search: 'Search',
    filter: 'Filter',
    export: 'Export',
    import: 'Import',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    warning: 'Warning',
    
    // Profile & Settings
    profile: 'Profile',
    settings: 'Settings',
    notifications: 'Notifications',
    language: 'Language',
    english: 'English',
    arabic: 'العربية',
    
    // Financial
    totalAssets: 'Total Assets',
    totalLiabilities: 'Total Liabilities',
    monthlyRevenue: 'Monthly Revenue',
    monthlyExpenses: 'Monthly Expenses',
    
    // Company
    companyName: 'Morgan Chemical ERP',
    
    // Inventory Management
    inventoryManagement: 'Inventory Management',
    addItem: 'Add Item',
    importCsv: 'Import CSV',
    exportCsv: 'Export CSV',
    createLabels: 'Create Labels',
    inventorySettings: 'Inventory Settings',
    warehouseSelector: 'Warehouse Selector',
    addWarehouse: 'Add Warehouse',
    editWarehouse: 'Edit Warehouse',
    allStock: 'All Stock',
    viewingInventory: 'Viewing inventory across',
    allWarehouses: 'all warehouses',
    viewingInventoryFor: 'Viewing inventory for',
    inventoryModule: 'Inventory',
    categories: 'Categories',
    searchInventory: 'Search inventory...',
    filterByStatus: 'Filter by status',
    filterByCategory: 'Filter by category',
    allStatuses: 'All Statuses',
    inStock: 'In Stock',
    outOfStock: 'Out of Stock',
    expired: 'Expired',
    allCategories: 'All Categories',
    productItem: 'Product',
    category: 'Category',
    batchNo: 'Batch No.',
    gs1Code: 'GS1 Code',
    type: 'Type',
    quantity: 'Quantity',
    location: 'Location',
    shelf: 'Shelf',
    price: 'Price',
    expiryDate: 'Expiry Date',
    actions: 'Actions',
    createLabel: 'Create Label',
    showHistory: 'Show History',
    previous: 'Previous',
    next: 'Next',
    page: 'Page',
    of: 'of',
    noProductsFound: 'No products found',
    tryAdjustingFilters: 'Try adjusting your filters',
    addFirstProduct: 'Add your first product to get started',
    addProduct: 'Add Product',
    
    // Dialog translations
    editProductInfo: 'Edit Product Information',
    addNewProduct: 'Add New Product',
    updateProductDetails: 'Update comprehensive product details and inventory information',
    registerNewProduct: 'Register a new pharmaceutical product with complete details and specifications',
    productHistory: 'Product History & Analytics',
    comprehensiveHistory: 'Comprehensive history and performance analytics for',
    loadingProductDetails: 'Loading product details...',
    
    // Inventory Settings Dialog
    configureInventoryOptions: 'Configure Inventory Dropdown Options',
    manageDropdownOptions: 'Manage the options available in Units of Measure, Product Types, Status Options, and Location Types dropdowns.',
    unitsOfMeasure: 'Units of Measure',
    itemTypes: 'Item Types',
    statusOptions: 'Status Options',
    locationTypes: 'Location Types',
    newUnitPlaceholder: 'New unit (e.g., mL, tablets)',
    newItemTypePlaceholder: 'New item type',
    newStatusPlaceholder: 'New status option',
    newLocationPlaceholder: 'New location type',
    done: 'Done',
    
    // Additional ProductForm translations
    chemicalName: 'Chemical Name',
    
    // Warehouse Dialogs
    editWarehouseDialog: 'Edit Warehouse',
    addNewWarehouse: 'Add New Warehouse',
    updateWarehouseDetails: 'Update the details for this warehouse',
    enterWarehouseDetails: 'Enter the details for the new warehouse',
    warehouseName: 'Name',
    warehouseLocation: 'Location',
    warehouseNamePlaceholder: 'Warehouse name',
    warehouseLocationPlaceholder: 'Warehouse location',
    warehouseUpdated: 'Warehouse updated',
    warehouseUpdatedSuccess: 'The warehouse details have been updated successfully.',
    warehouseAdded: 'Warehouse added',
    warehouseAddedSuccess: 'The new warehouse has been added successfully.',
    saveChanges: 'Save Changes',
    addWarehouseBtn: 'Add Warehouse',
    transferProductToWarehouse: 'Transfer Product to Another Warehouse',
    transferStockDescription: 'Transfer stock from the current warehouse to a different warehouse location',
    productDetails: 'Product Details',
    productName: 'Product',
    currentStock: 'Current Stock',
    currentWarehouse: 'Current Warehouse',
    unknown: 'Unknown',
    targetWarehouse: 'Target Warehouse',
    selectTargetWarehouse: 'Select target warehouse',
    transferQuantity: 'Transfer Quantity',
    enterQuantityToTransfer: 'Enter quantity to transfer',
    maximum: 'Maximum',
    transferNotesOptional: 'Transfer Notes (Optional)',
    addTransferNotes: 'Add any notes about this transfer...',
    transferInitiated: 'Transfer Initiated',
    transferringProduct: 'Transferring',
    from: 'from',
    to: 'to',
    confirmTransfer: 'Confirm Transfer',
    
    // Product History Dialog
    productInformation: 'Product Information',
    skuCode: 'SKU Code',
    manufacturer: 'Manufacturer',
    inventoryDetails: 'Inventory Details',
    currentQuantity: 'Current Quantity',
    inventoryWarehouseLocation: 'Warehouse Location',
    mainWarehouse: 'Main Warehouse',
    reorderLevel: 'Reorder Level',
    stockValue: 'Stock Value',
    lastStockMovement: 'Last Stock Movement',
    unitsReceived: 'units received on',
    averageMonthlyUsage: 'Average Monthly Usage',
    month: 'month',
    pricingInformation: 'Pricing Information',
    profitMargin: 'Profit Margin',
    profitPerUnit: 'Profit per Unit',
    lastPriceUpdate: 'Last Price Update',
    priceTrend: 'Price Trend',
    increasing: 'Increasing',
    complianceQuality: 'Compliance & Quality',
    batchNumber: 'Batch Number',
    qualityStatus: 'Quality Status',
    approved: 'Approved',
    lastQualityCheck: 'Last Quality Check',
    regulatoryStatus: 'Regulatory Status',
    edaApproved: 'EDA Approved - License',
    activityTimeline: 'Activity Timeline',
    productInfoUpdated: 'Product Information Updated',
    quantityChanged: 'Quantity changed from 150 to',
    updatedBy: 'Updated by: System Administrator',
    stockReceived: 'Stock Received',
    receivedUnits: 'Received',
    fromSupplier: 'from supplier',
    purchaseOrder: 'Purchase Order',
    labelGenerated: 'Label Generated',
    productLabelCreated: 'Product label created for batch',
    labelType: 'Label Type: Pharmaceutical Grade',
    productAddedInventory: 'Product Added to Inventory',
    initialStock: 'Initial stock',
    createdBy: 'Created by: Inventory Manager',
    close: 'Close',
    exportReport: 'Export Report',
    transferToWarehouse: 'Transfer to Warehouse',
    editProduct: 'Edit Product',
    
    // Categories Management
    'Manage product categories used in inventory and sales': 'Manage product categories used in inventory and sales',
    'No categories found': 'No categories found',
    'Add your first category below': 'Add your first category below',
    'Name': 'Name',
    'Description': 'Description',
    'Category Name': 'Category Name',
    'Description (optional)': 'Description (optional)',
    'Adding...': 'Adding...',
    'Add Category': 'Add Category',
    'Confirm Deletion': 'Confirm Deletion',
    'Are you sure you want to delete the category': 'Are you sure you want to delete the category',
    'This action cannot be undone': 'This action cannot be undone',
    'Cancel': 'Cancel',
    'Deleting...': 'Deleting...',
    'Delete': 'Delete',
    'manageCategories': 'Manage Categories',
    'more': 'more',
    'categoriesDescription': 'Click "Manage Categories" to add, edit, or delete product categories',
    
    // Create Invoice
    createInvoiceModule: 'Create Invoice',
    invoiceManagement: 'Invoice Management',
    createNewInvoicesAndManageDrafts: 'Create new invoices and manage your drafts',
    customerInfo: 'Customer Information',
    chooseCustomer: 'Choose Customer',
    customerName: 'Customer Name',
    company: 'Company',
    position: 'Position',
    emailInvoice: 'Email',
    phoneInvoice: 'Phone',
    sectorInvoice: 'Sector',
    addressInvoice: 'Address',
    taxNumberInvoice: 'Tax Number',
    invoiceItems: 'Invoice Items',
    selectProduct: 'Select Product',
    invoiceProductName: 'Product Name',
    unitPrice: 'Unit Price',
    total: 'Total',
    addInvoiceItem: 'Add Item',
    removeItem: 'Remove Item',
    subtotal: 'Subtotal',
    discount: 'Discount',
    tax: 'Tax',
    grandTotal: 'Grand Total',
    paymentInfo: 'Payment Information',
    paymentStatus: 'Payment Status',
    paymentMethod: 'Payment Method',
    amountPaid: 'Amount Paid',
    generateInvoice: 'Generate Invoice',
    printInvoice: 'Print Invoice',
    downloadPdf: 'Download PDF',
    paid: 'Paid',
    unpaid: 'Unpaid',
    partial: 'Partial',
    cash: 'Cash',
    visa: 'Visa',
    cheque: 'Cheque',
    bankTransfer: 'Bank Transfer',
    etaNumber: 'ETA Number',
    
    // Dashboard
    welcomeToPremier: 'Welcome to Premier ERP',
    yourBusinessOverview: 'Your business overview',
    financialSummary: 'Financial Summary',
    operationalMetrics: 'Operational Metrics',
    inventoryAlerts: 'Inventory Alerts',
    salesOverview: 'Sales Overview',
    salesDistribution: 'Sales Distribution',
    categoryPerformance: 'Category Performance',
    totalRevenue: 'Total Revenue',
    totalExpenses: 'Total Expenses',
    netProfit: 'Net Profit',
    cashBalance: 'Cash Balance',
    pendingOrders: 'Pending Orders',
    outstandingAR: 'Outstanding A/R',
    totalAccounts: 'Total Accounts',
    trialBalance: 'Trial Balance',
    lowStockItems: 'Low Stock Items',
    expiringProducts: 'Expiring Products',
    warehouseBreakdown: 'Warehouse Breakdown',
    viewDetails: 'View Details',
    
    // Expiring Products Card
    expired: 'Expired',
    expiring: 'Expiring',
    expiresToday: 'Expires today',
    expiresTomorrow: 'Expires tomorrow',
    daysLeft: '{days} days left',
    noExpiry: 'No expiry',
    errorLoadingExpiryData: 'Error Loading Expiry Data',
    unableToLoadExpiry: 'Unable to load expiry information. Please try again later.',
    noProductsExpiringSoon: 'No products expiring soon!',
    stock: 'Stock',
    showLess: 'Show Less',
    showAllItems: 'Show All {count} Items',
    
    // Low Stock Card
    lowStockProducts: 'Low Stock Products',
    lowStockAlert: 'Low Stock Alert',
    errorLoadingStockData: 'Error Loading Stock Data',
    unableToLoadStock: 'Unable to load stock information. Please try again later.',
    outOfStock: 'Out',
    low: 'Low',
    allProductsWellStocked: 'All products are well stocked!',
    reorder: 'Reorder',
    
    // Dashboard Chart Dialogs
    salesOverviewEnhanced: 'Sales Overview - Enhanced View',
    salesAnalytics: 'Sales Analytics',
    peakMonth: 'Peak Month',
    december: 'December',
    sales: 'Sales',
    growthRate: 'Growth Rate',
    yoy: 'YoY',
    trendingUp: 'Trending Up',
    average: 'Average',
    monthly: 'Monthly',
    targetMet: 'Target Met',
    thisYear: 'This Year',
    target: 'Target',
    salesDistributionEnhanced: 'Sales Distribution - Enhanced View',
    distributionDetails: 'Distribution Details',
    categoryPerformanceEnhanced: 'Category Performance - Enhanced View',
    performanceMetrics: 'Performance Metrics',
    vsLastMonth: 'vs Last Month',
    
    // Accounting Module
    accountingDashboard: 'Accounting Dashboard',
    chartOfAccounts: 'Chart of Accounts',
    journalEntries: 'Journal Entries',
    customerPayments: 'Customer Payments',
    profitAndLoss: 'Profit & Loss',
    balanceSheet: 'Balance Sheet',
    trialBalanceReport: 'Trial Balance Report',
    accountingPeriods: 'Accounting Periods',
    financialIntegration: 'Financial Integration',
    
    // Expenses Module
    expenseManagement: 'Expense Management',
    addExpense: 'Add Expense',
    expenseCategory: 'Expense Category',
    expenseAmount: 'Amount',
    expenseDate: 'Date',
    expenseDescription: 'Description',
    paymentMethodExpense: 'Payment Method',
    costCenter: 'Cost Center',
    receiptUpload: 'Receipt Upload',
    expenseStatus: 'Expense Status',
    
    // Reports Module
    reportsAnalytics: 'Reports & Analytics',
    inventoryReports: 'Inventory Reports',
    salesReports: 'Sales Reports',
    financialReports: 'Financial Reports',
    customerReports: 'Customer Reports',
    supplierReports: 'Supplier Reports',
    exportReport: 'Export Report',
    generateReport: 'Generate Report',
    reportPeriod: 'Report Period',
    
    // Procurement Module
    procurementManagement: 'Procurement Management',
    createPurchaseOrder: 'Create Purchase Order',
    purchaseOrderHistory: 'Purchase Order History',
    selectSupplier: 'Select Supplier',
    expectedDelivery: 'Expected Delivery',
    procurementStatus: 'Procurement Status',
    approvalRequired: 'Approval Required',
    
    // Order Management
    orderManagementSystem: 'Order Management System',
    newOrder: 'New Order',
    orderStatus: 'Order Status',
    orderNumber: 'Order Number',
    orderDate: 'Order Date',
    deliveryDate: 'Delivery Date',
    orderTotal: 'Order Total',
    
    // User Management
    userManagementSystem: 'User Management System',
    addUser: 'Add User',
    userName: 'User Name',
    userEmail: 'Email',
    userRole: 'User Role',
    userStatus: 'User Status',
    userPermissions: 'User Permissions',
    lastLogin: 'Last Login',
    
    // System Preferences
    systemPreferencesTitle: 'System Preferences',
    companySettings: 'Company Settings',
    currencySettings: 'Currency Settings',
    taxSettings: 'Tax Settings',
    notificationSettings: 'Notification Settings',
    backupSettings: 'Backup Settings',
    securitySettings: 'Security Settings',
    
    // Common Actions
    view: 'View',
    create: 'Create',
    update: 'Update',
    deleteAction: 'Delete',
    confirm: 'Confirm',
    cancelAction: 'Cancel',
    saveChanges: 'Save Changes',
    discardChanges: 'Discard Changes',
    refresh: 'Refresh',
    print: 'Print',
    download: 'Download',
    upload: 'Upload',
    
    // Status Messages
    successMessage: 'Operation successful',
    errorMessage: 'An error occurred',
    loadingMessage: 'Loading...',
    savingMessage: 'Saving...',
    deletingMessage: 'Deleting...',
    noDataFound: 'No data found',
    
    // Time periods
    today: 'Today',
    yesterday: 'Yesterday',
    thisWeek: 'This Week',
    lastWeek: 'Last Week',
    thisMonth: 'This Month',
    lastMonth: 'Last Month',
    thisYear: 'This Year',
    lastYear: 'Last Year',
    customRange: 'Custom Range',
    
    // Dashboard additions
    currentMonthRevenue: 'Current month revenue',
    revenueMinusExpenses: 'Revenue minus expenses',
    pendingInvoices: 'pending invoices',
    ordersPending: 'orders pending',
    expenseEntries: 'expense entries',
    availableCashFlow: 'Available cash flow',
    paymentsReceived: 'Payments Received',
    thisMonthPayments: 'This month payments',
    inventoryValue: 'Inventory Value',
    costValue: 'Cost value',
    selling: 'Selling',
    warehouses: 'warehouses',
    newThisMonth: 'new this month',
    fromLastMonth: 'from last month',
    todaySales: 'Today Sales',
    daily: 'Daily',
    monthSales: 'Month Sales',
    monthly: 'Monthly',
    collectedTax: 'Collected Tax',
    vatCollectedFromSales: 'VAT collected from sales',
    salesOverview: 'Sales Overview',
    salesDistribution: 'Sales Distribution',
    categoryPerformance: 'Category Performance',
    inventoryValueBreakdown: 'Inventory Value Breakdown',
    realTimeWarehouseAnalysis: 'Real-time warehouse inventory analysis',
    loadingWarehouseBreakdown: 'Loading warehouse breakdown',
    totalCostValue: 'Total Cost Value',
    totalSellingValue: 'Total Selling Value',
    totalQuantity: 'Total Quantity',
    units: 'units',
    sellingValue: 'Selling Value',
    avgUnitCost: 'Avg Unit Cost',
    
    // Login page
    signInToAccount: 'Sign in to your account',
    welcomeBack: 'Welcome Back',
    signInPrompt: 'Sign in to your Premier ERP account',
    email: 'Email',
    enterEmail: 'Enter your email',
    password: 'Password',
    enterPassword: 'Enter your password',
    signIn: 'Sign In',
    secureERPSystem: 'Secure Premier ERP system',
    enterpriseSecurity: 'Enterprise Security',
    termsAndPrivacy: 'By signing in, you agree to our Terms of Service and Privacy Policy',
    
    // Customer Management
    customerRecords: 'Customer Records',
    allCustomers: 'All Customers',
    activeCustomers: 'Active Customers',
    inactiveCustomers: 'Inactive Customers',
    viewProfile: 'View Profile',
    viewOrders: 'View Orders',
    editCustomer: 'Edit Customer',
    deleteCustomer: 'Delete Customer',
    customerDeleted: 'Customer deleted successfully',
    importCustomers: 'Import Customers',
    exportCustomers: 'Export Customers',
    addCustomer: 'Add Customer',
    searchCustomers: 'Search customers by name, email or phone',
    filterByStatus: 'Filter by Status',
    showingResults: 'Showing results',
    noCustomersFound: 'No customers found',
    tryDifferentSearch: 'Try adjusting your search criteria',
    loadingCustomers: 'Loading customers...',
    
    // Customer Analytics
    reportsAnalytics: 'Reports & Analytics',
    totalCustomers: 'Total Customers',
    active: 'Active',
    newThisMonth: 'New This Month',
    avgOrderValue: 'Avg Order Value',
    perCustomer: 'Per customer',
    repeatCustomers: 'Repeat Customers',
    retentionRate: 'Retention rate',
    customerDistributionBySector: 'Customer Distribution by Sector',
    topCustomersByRevenue: 'Top Customers by Revenue',
    geographicDistribution: 'Geographic Distribution',
    customers: 'customers',
    
    // Additional Customer Page translations
    customerManagement: 'Customer Management',
    manageClients: 'Manage Clients',
    activeSectors: 'Active Sectors',
    industryTypes: 'Industry Types',
    customerValue: 'Customer Value',
    totalPortfolio: 'Total Portfolio',
    recentAdditions: 'Recent Additions',
    topSector: 'Top Sector',
    geographicSpread: 'Geographic Spread',
    cities: 'Cities',
    coverageArea: 'Coverage Area',
    monthlyIncrease: 'Monthly Increase',
    errorLoadingCustomers: 'Error loading customers',
    pleaseTryAgainLater: 'Please try again later',
    noMatchingCustomersFound: 'No matching customers found',
    tryAdjustingSearchQuery: 'Try adjusting your search query',
    noCustomersAvailable: 'No customers available',
    action: 'Action',
    customerReportsAnalytics: 'Customer Reports & Analytics',
    comprehensiveReportsInsights: 'Comprehensive reports and insights',
    exportPDF: 'Export PDF',
    loadingReports: 'Loading reports...',
    customerRevenue: 'Customer Revenue',
    monthlyGrowthTrend: 'Monthly Growth Trend',
    activeAccounts: 'Active Accounts',
    
    // Create Invoice page
    draftInvoices: 'Draft Invoices',
    createNewInvoice: 'Create New Invoice',
    createInvoiceDescription: 'Create a new invoice by selecting a customer and adding products',
    saveAsDraft: 'Save as Draft',
    previewInvoice: 'Preview Invoice',
    invoicesInProgress: 'Invoices In Progress',
    resetToInvoice1: 'Reset to Invoice 1',
    newInvoice: 'New Invoice',
    invoiceProgressAutoSaved: 'Your invoice progress is automatically saved. You can work on up to 4 invoices at the same time.',
    nextInvoiceNumber: 'Next Invoice #',
    customerInformation: 'Customer Information',
    selectOrCreateCustomer: 'Select an existing customer or create a new one',
    customer: 'Customer',
    selectCustomer: 'Select customer...',
    searchCustomer: 'Search customer...',
    noCustomersFoundFor: 'No customers found for',
    createNewCustomer: 'Create New Customer',
    typeToSearchCustomers: 'Type to search customers...',
    paperInvoiceNumber: 'Paper Invoice Number',
    paperInvoiceNumberPlaceholder: 'P-2025001',
    physicalInvoiceReference: 'Physical invoice reference number for record-keeping',
    approvalNumber: 'Approval No.',
    approvalNumberPlaceholder: 'APP-2025001',
    internalApprovalReference: 'Internal approval reference number',
    code: 'Code',
    mobile: 'Mobile',
    etaNumber: 'ETA Number',
    sector: 'Sector',
    email: 'Email',
    address: 'Address',
    newCustomer: 'New Customer',
    companyName: 'Company Name',
    companyNamePlaceholder: 'Company name',
    name: 'Name',
    customerNamePlaceholder: 'Customer name',
    position: 'Position',
    jobTitlePositionPlaceholder: 'Job title/Position',
    phone: 'Phone',
    phoneNumberPlaceholder: 'Phone number',
    businessSectorPlaceholder: 'Business sector',
    taxNumberEtaRegistration: 'Tax Number (ETA Registration)',
    egyptianTaxAuthorityPlaceholder: 'Egyptian Tax Authority registration number',
    requiredForEtaPortal: 'Required for invoices to appear in customer\'s ETA portal',
    customerEmailPlaceholder: 'customer@example.com',
    customerAddressPlaceholder: 'Customer address',
    saveCustomer: 'Save Customer',
    invoiceItems: 'Invoice Items',
    addProductsToInvoice: 'Add products to this invoice'
  },
  ar: {
    // Navigation
    dashboard: 'لوحة التحكم',
    products: 'المنتجات',
    inventory: 'المخزون',
    expenses: 'المصروفات',
    accounting: 'المحاسبة',
    suppliers: 'الموردين',
    customers: 'العملاء',
    createInvoice: 'إنشاء فاتورة',
    createQuotation: 'إنشاء عرض سعر',
    invoiceHistory: 'تاريخ الفواتير',
    quotationHistory: 'تاريخ عروض الأسعار',
    orderManagement: 'إدارة الطلبات',
    ordersHistory: 'تاريخ الطلبات',
    label: 'تسمية',
    reports: 'التقارير',
    procurement: 'المشتريات',
    userManagement: 'إدارة المستخدمين',
    systemPreferences: 'إعدادات النظام',
    logout: 'تسجيل الخروج',
    
    // Common
    save: 'حفظ',
    cancel: 'إلغاء',
    edit: 'تعديل',
    delete: 'حذف',
    add: 'إضافة',
    search: 'بحث',
    filter: 'فلتر',
    export: 'تصدير',
    import: 'استيراد',
    loading: 'جاري التحميل...',
    error: 'خطأ',
    success: 'نجح',
    warning: 'تحذير',
    
    // Profile & Settings
    profile: 'الملف الشخصي',
    settings: 'الإعدادات',
    notifications: 'الإشعارات',
    language: 'اللغة',
    english: 'English',
    arabic: 'العربية',
    
    // Financial
    totalAssets: 'إجمالي الأصول',
    totalLiabilities: 'إجمالي الخصوم',
    monthlyRevenue: 'الإيرادات الشهرية',
    monthlyExpenses: 'المصروفات الشهرية',
    
    // Company
    companyName: 'نظام إدارة موارد مورجان الكيميائية',
    
    // Inventory Management
    inventoryManagement: 'إدارة المخزون',
    addItem: 'إضافة عنصر',
    importCsv: 'استيراد CSV',
    exportCsv: 'تصدير CSV',
    createLabels: 'إنشاء ملصقات',
    inventorySettings: 'إعدادات المخزون',
    warehouseSelector: 'محدد المستودع',
    addWarehouse: 'إضافة مستودع',
    editWarehouse: 'تعديل المستودع',
    allStock: 'جميع المخزون',
    viewingInventory: 'عرض المخزون عبر',
    allWarehouses: 'جميع المستودعات',
    viewingInventoryFor: 'عرض المخزون لـ',
    inventoryModuleAr: 'المخزون',
    categories: 'الفئات',
    searchInventory: 'البحث في المخزون...',
    filterByStatus: 'فلتر حسب الحالة',
    filterByCategory: 'فلتر حسب الفئة',
    allStatuses: 'جميع الحالات',
    inStock: 'متوفر',
    outOfStock: 'نفد المخزون',
    expired: 'منتهي الصلاحية',
    allCategories: 'جميع الفئات',
    product: 'المنتج',
    category: 'الفئة',
    batchNo: 'رقم الدفعة',
    gs1Code: 'كود GS1',
    type: 'النوع',
    quantity: 'الكمية',
    location: 'الموقع',
    shelf: 'الرف',
    price: 'السعر',
    expiryDate: 'تاريخ الانتهاء',
    actions: 'الإجراءات',
    createLabel: 'إنشاء ملصق',
    showHistory: 'عرض التاريخ',
    previous: 'السابق',
    next: 'التالي',
    page: 'صفحة',
    of: 'من',
    noProductsFound: 'لم يتم العثور على منتجات',
    tryAdjustingFilters: 'جرب تعديل المرشحات',
    addFirstProduct: 'أضف منتجك الأول للبدء',
    addProduct: 'إضافة منتج',
    
    // Dialog translations
    editProductInfo: 'تحرير معلومات المنتج',
    addNewProduct: 'إضافة منتج جديد',
    updateProductDetails: 'تحديث تفاصيل المنتج الشاملة ومعلومات المخزون',
    registerNewProduct: 'تسجيل منتج صيدلاني جديد بتفاصيل ومواصفات كاملة',
    productHistory: 'تاريخ المنتج والتحليلات',
    comprehensiveHistory: 'تاريخ شامل وتحليلات الأداء لـ',
    loadingProductDetails: 'جاري تحميل تفاصيل المنتج...',
    
    // Inventory Settings Dialog
    configureInventoryOptions: 'تكوين خيارات القوائم المنسدلة للمخزون',
    manageDropdownOptions: 'إدارة الخيارات المتاحة في وحدات القياس وأنواع المنتجات وخيارات الحالة وأنواع المواقع.',
    unitsOfMeasure: 'وحدات القياس',
    itemTypes: 'أنواع العناصر',
    statusOptions: 'خيارات الحالة',
    locationTypes: 'أنواع المواقع',
    newUnitPlaceholder: 'وحدة جديدة (مثل: مل، أقراص)',
    newItemTypePlaceholder: 'نوع عنصر جديد',
    newStatusPlaceholder: 'خيار حالة جديد',
    newLocationPlaceholder: 'نوع موقع جديد',
    done: 'تم',
    
    // Additional ProductForm translations
    drugName: 'اسم الدواء',
    chemicalName: 'الاسم الكيميائي',
    description: 'الوصف',
    unitOfMeasure: 'وحدة القياس',
    lowStockThreshold: 'حد المخزون المنخفض',
    costPrice: 'سعر التكلفة',
    sellingPrice: 'سعر البيع',
    warehouse: 'المستودع',
    shelfNumber: 'رقم الرف',
    status: 'الحالة',
    productType: 'نوع المنتج',
    
    // Form buttons
    saving: 'جاري الحفظ...',
    saveProduct: 'حفظ المنتج',
    updateProduct: 'تحديث المنتج',
    
    // Warehouse Dialogs
    editWarehouseDialogAr: 'تعديل المستودع',
    addNewWarehouse: 'إضافة مستودع جديد',
    updateWarehouseDetails: 'تحديث تفاصيل هذا المستودع',
    enterWarehouseDetails: 'أدخل تفاصيل المستودع الجديد',
    warehouseNameAr: 'الاسم',
    warehouseLocationAr: 'الموقع',
    warehouseNamePlaceholder: 'اسم المستودع',
    warehouseLocationPlaceholder: 'موقع المستودع',
    warehouseUpdated: 'تم تحديث المستودع',
    warehouseUpdatedSuccess: 'تم تحديث تفاصيل المستودع بنجاح.',
    warehouseAdded: 'تم إضافة المستودع',
    warehouseAddedSuccess: 'تم إضافة المستودع الجديد بنجاح.',
    saveChanges: 'حفظ التغييرات',
    addWarehouseBtnAr: 'إضافة مستودع',
    transferProductToWarehouse: 'نقل المنتج إلى مستودع آخر',
    transferStockDescription: 'نقل المخزون من المستودع الحالي إلى موقع مستودع مختلف',
    productDetails: 'تفاصيل المنتج',
    productNameAr: 'المنتج',
    currentStock: 'المخزون الحالي',
    currentWarehouse: 'المستودع الحالي',
    unknown: 'غير معروف',
    targetWarehouse: 'المستودع المستهدف',
    selectTargetWarehouse: 'اختر المستودع المستهدف',
    transferQuantity: 'كمية النقل',
    enterQuantityToTransfer: 'أدخل الكمية المراد نقلها',
    maximum: 'الحد الأقصى',
    transferNotesOptional: 'ملاحظات النقل (اختيارية)',
    addTransferNotes: 'أضف أي ملاحظات حول هذا النقل...',
    transferInitiated: 'تم بدء النقل',
    transferringProduct: 'نقل',
    from: 'من',
    to: 'إلى',
    confirmTransfer: 'تأكيد النقل',
    
    // Product History Dialog
    productInformation: 'معلومات المنتج',
    skuCode: 'رمز المنتج',
    manufacturer: 'الشركة المصنعة',
    inventoryDetails: 'تفاصيل المخزون',
    currentQuantity: 'الكمية الحالية',
    warehouseLocation: 'موقع المستودع',
    mainWarehouse: 'المستودع الرئيسي',
    reorderLevel: 'مستوى إعادة الطلب',
    stockValue: 'قيمة المخزون',
    lastStockMovement: 'آخر حركة مخزون',
    unitsReceived: 'وحدة تم استلامها في',
    averageMonthlyUsage: 'متوسط الاستخدام الشهري',
    month: 'شهر',
    pricingInformation: 'معلومات التسعير',
    profitMargin: 'هامش الربح',
    profitPerUnit: 'الربح لكل وحدة',
    lastPriceUpdate: 'آخر تحديث للسعر',
    priceTrend: 'اتجاه السعر',
    increasing: 'متزايد',
    complianceQuality: 'الامتثال والجودة',
    batchNumber: 'رقم الدفعة',
    qualityStatus: 'حالة الجودة',
    approved: 'موافق عليه',
    lastQualityCheck: 'آخر فحص جودة',
    regulatoryStatus: 'الحالة التنظيمية',
    edaApproved: 'معتمد من EDA - ترخيص',
    activityTimeline: 'الجدول الزمني للأنشطة',
    productInfoUpdated: 'تم تحديث معلومات المنتج',
    quantityChanged: 'تم تغيير الكمية من 150 إلى',
    updatedBy: 'محدث من: مدير النظام',
    stockReceived: 'تم استلام المخزون',
    receivedUnits: 'تم استلام',
    fromSupplier: 'من المورد',
    purchaseOrder: 'أمر الشراء',
    labelGenerated: 'تم إنشاء الملصق',
    productLabelCreated: 'تم إنشاء ملصق المنتج للدفعة',
    labelType: 'نوع الملصق: درجة صيدلانية',
    productAddedInventory: 'تم إضافة المنتج إلى المخزون',
    initialStock: 'المخزون الأولي',
    createdBy: 'تم إنشاؤه بواسطة: مدير المخزون',
    close: 'إغلاق',
    exportReport: 'تصدير التقرير',
    transferToWarehouse: 'نقل إلى المستودع',
    editProduct: 'تعديل المنتج',
    
    // Categories Management
    'Manage product categories used in inventory and sales': 'إدارة فئات المنتجات المستخدمة في المخزون والمبيعات',
    'No categories found': 'لم يتم العثور على فئات',
    'Add your first category below': 'أضف فئتك الأولى أدناه',
    'Name': 'الاسم',
    'Description': 'الوصف',
    'Category Name': 'اسم الفئة',
    'Description (optional)': 'الوصف (اختياري)',
    'Adding...': 'جاري الإضافة...',
    'Add Category': 'إضافة فئة',
    'Confirm Deletion': 'تأكيد الحذف',
    'Are you sure you want to delete the category': 'هل أنت متأكد من أنك تريد حذف الفئة',
    'This action cannot be undone': 'لا يمكن التراجع عن هذا الإجراء',
    'Cancel': 'إلغاء',
    'Deleting...': 'جاري الحذف...',
    'Delete': 'حذف',
    'manageCategories': 'إدارة الفئات',
    'more': 'المزيد',
    'categoriesDescription': 'انقر على "إدارة الفئات" لإضافة أو تعديل أو حذف فئات المنتجات',

    // Create Invoice
    createInvoiceArabic: 'إنشاء فاتورة',
    invoiceManagement: 'إدارة الفواتير',
    createNewInvoicesAndManageDrafts: 'إنشاء فواتير جديدة وإدارة المسودات',
    customerInfo: 'معلومات العميل',
    chooseCustomer: 'اختر العميل',
    customerName: 'اسم العميل',
    company: 'الشركة',
    position: 'المنصب',
    emailInvoice: 'البريد الإلكتروني',
    phoneInvoice: 'الهاتف',
    sectorInvoice: 'القطاع',
    addressInvoice: 'العنوان',
    taxNumberInvoice: 'الرقم الضريبي',
    invoiceItems: 'عناصر الفاتورة',
    selectProduct: 'اختر المنتج',
    productName: 'اسم المنتج',
    unitPrice: 'سعر الوحدة',
    total: 'المجموع',
    addInvoiceItem: 'إضافة عنصر',
    removeItem: 'إزالة العنصر',
    subtotal: 'المجموع الفرعي',
    discount: 'الخصم',
    tax: 'الضريبة',
    grandTotal: 'الإجمالي الكلي',
    paymentInfo: 'معلومات الدفع',
    paymentStatus: 'حالة الدفع',
    paymentMethod: 'طريقة الدفع',
    amountPaid: 'المبلغ المدفوع',
    generateInvoice: 'إنشاء الفاتورة',
    printInvoice: 'طباعة الفاتورة',
    downloadPdf: 'تحميل PDF',
    paid: 'مدفوع',
    unpaid: 'غير مدفوع',
    partial: 'جزئي',
    cash: 'نقداً',
    visa: 'فيزا',
    cheque: 'شيك',
    bankTransfer: 'تحويل بنكي',
    etaNumber: 'رقم ETA',
    
    // Dashboard
    welcomeToPremier: 'مرحبا بك في بريمير ERP',
    yourBusinessOverview: 'نظرة عامة على أعمالك',
    financialSummary: 'الملخص المالي',
    operationalMetrics: 'المقاييس التشغيلية',
    inventoryAlerts: 'تنبيهات المخزون',
    salesOverview: 'نظرة عامة على المبيعات',
    salesDistribution: 'توزيع المبيعات',
    categoryPerformance: 'أداء الفئات',
    totalRevenue: 'إجمالي الإيرادات',
    totalExpenses: 'إجمالي المصروفات',
    netProfit: 'صافي الربح',
    cashBalance: 'الرصيد النقدي',
    pendingOrders: 'الطلبات المعلقة',
    outstandingAR: 'المديونيات المستحقة',
    totalAccounts: 'إجمالي الحسابات',
    trialBalance: 'ميزان المراجعة',
    lowStockItems: 'عناصر المخزون المنخفض',
    expiringProducts: 'المنتجات المنتهية الصلاحية',
    warehouseBreakdown: 'توزيع المستودعات',
    viewDetails: 'عرض التفاصيل',
    
    // Expiring Products Card
    expired: 'منتهي الصلاحية',
    expiring: 'قارب على الانتهاء',
    expiresToday: 'ينتهي اليوم',
    expiresTomorrow: 'ينتهي غداً',
    daysLeft: '{days} يوم متبقي',
    noExpiry: 'لا يوجد تاريخ انتهاء',
    errorLoadingExpiryData: 'خطأ في تحميل بيانات الصلاحية',
    unableToLoadExpiry: 'غير قادر على تحميل معلومات الصلاحية. يرجى المحاولة مرة أخرى لاحقاً.',
    noProductsExpiringSoon: 'لا توجد منتجات قاربت على انتهاء الصلاحية!',
    stock: 'المخزون',
    showLess: 'عرض أقل',
    showAllItems: 'عرض جميع العناصر {count}',
    
    // Low Stock Card
    lowStockProducts: 'منتجات المخزون المنخفض',
    lowStockAlert: 'تنبيه المخزون المنخفض',
    errorLoadingStockData: 'خطأ في تحميل بيانات المخزون',
    unableToLoadStock: 'غير قادر على تحميل معلومات المخزون. يرجى المحاولة مرة أخرى لاحقاً.',
    outOfStock: 'نفذ',
    low: 'منخفض',
    allProductsWellStocked: 'جميع المنتجات بمخزون جيد!',
    reorder: 'إعادة الطلب',
    
    // Dashboard Chart Dialogs
    salesOverviewEnhanced: 'نظرة عامة على المبيعات - عرض محسّن',
    salesAnalytics: 'تحليلات المبيعات',
    peakMonth: 'شهر الذروة',
    december: 'ديسمبر',
    sales: 'المبيعات',
    growthRate: 'معدل النمو',
    yoy: 'سنة بعد سنة',
    trendingUp: 'في تصاعد',
    average: 'المتوسط',
    monthly: 'شهري',
    targetMet: 'تم تحقيق الهدف',
    thisYear: 'هذا العام',
    target: 'الهدف',
    salesDistributionEnhanced: 'توزيع المبيعات - عرض محسّن',
    distributionDetails: 'تفاصيل التوزيع',
    categoryPerformanceEnhanced: 'أداء الفئات - عرض محسّن',
    performanceMetrics: 'مقاييس الأداء',
    vsLastMonth: 'مقارنة بالشهر الماضي',
    
    // Accounting Module
    accountingDashboard: 'لوحة المحاسبة',
    chartOfAccounts: 'دليل الحسابات',
    journalEntries: 'القيود اليومية',
    customerPayments: 'مدفوعات العملاء',
    profitAndLoss: 'الأرباح والخسائر',
    balanceSheet: 'الميزانية العمومية',
    trialBalanceReport: 'تقرير ميزان المراجعة',
    accountingPeriods: 'الفترات المحاسبية',
    financialIntegration: 'التكامل المالي',
    
    // Expenses Module
    expenseManagement: 'إدارة المصروفات',
    addExpense: 'إضافة مصروف',
    expenseCategory: 'فئة المصروف',
    expenseAmount: 'المبلغ',
    expenseDate: 'التاريخ',
    expenseDescription: 'الوصف',
    paymentMethodExpense: 'طريقة الدفع',
    costCenter: 'مركز التكلفة',
    receiptUpload: 'رفع الإيصال',
    expenseStatus: 'حالة المصروف',
    
    // Reports Module
    reportsAnalytics: 'التقارير والتحليلات',
    inventoryReports: 'تقارير المخزون',
    salesReports: 'تقارير المبيعات',
    financialReports: 'التقارير المالية',
    customerReports: 'تقارير العملاء',
    supplierReports: 'تقارير الموردين',
    exportReport: 'تصدير التقرير',
    generateReport: 'إنشاء التقرير',
    reportPeriod: 'فترة التقرير',
    
    // Procurement Module
    procurementManagement: 'إدارة المشتريات',
    createPurchaseOrder: 'إنشاء أمر شراء',
    purchaseOrderHistory: 'تاريخ أوامر الشراء',
    selectSupplier: 'اختر المورد',
    expectedDelivery: 'التسليم المتوقع',
    procurementStatus: 'حالة المشتريات',
    approvalRequired: 'يتطلب الموافقة',
    
    // Order Management
    orderManagementSystem: 'نظام إدارة الطلبات',
    newOrder: 'طلب جديد',
    orderStatus: 'حالة الطلب',
    orderNumber: 'رقم الطلب',
    orderDate: 'تاريخ الطلب',
    deliveryDate: 'تاريخ التسليم',
    orderTotal: 'إجمالي الطلب',
    
    // User Management
    userManagementSystem: 'نظام إدارة المستخدمين',
    addUser: 'إضافة مستخدم',
    userName: 'اسم المستخدم',
    userEmail: 'البريد الإلكتروني',
    userRole: 'دور المستخدم',
    userStatus: 'حالة المستخدم',
    userPermissions: 'صلاحيات المستخدم',
    lastLogin: 'آخر دخول',
    
    // System Preferences
    systemPreferencesTitle: 'إعدادات النظام',
    companySettings: 'إعدادات الشركة',
    currencySettings: 'إعدادات العملة',
    taxSettings: 'إعدادات الضرائب',
    notificationSettings: 'إعدادات الإشعارات',
    backupSettings: 'إعدادات النسخ الاحتياطي',
    securitySettings: 'إعدادات الأمان',
    
    // Common Actions
    view: 'عرض',
    create: 'إنشاء',
    update: 'تحديث',
    deleteAction: 'حذف',
    confirm: 'تأكيد',
    cancelAction: 'إلغاء',
    saveChanges: 'حفظ التغييرات',
    discardChanges: 'تجاهل التغييرات',
    refresh: 'تحديث',
    print: 'طباعة',
    download: 'تحميل',
    upload: 'رفع',
    
    // Status Messages
    successMessage: 'تمت العملية بنجاح',
    errorMessage: 'حدث خطأ',
    loadingMessage: 'جاري التحميل...',
    savingMessage: 'جاري الحفظ...',
    deletingMessage: 'جاري الحذف...',
    noDataFound: 'لا توجد بيانات',
    
    // Time periods
    today: 'اليوم',
    yesterday: 'أمس',
    thisWeek: 'هذا الأسبوع',
    lastWeek: 'الأسبوع الماضي',
    thisMonth: 'هذا الشهر',
    lastMonth: 'الشهر الماضي',
    thisYear: 'هذه السنة',
    lastYear: 'السنة الماضية',
    customRange: 'نطاق مخصص',
    
    // Dashboard additions
    currentMonthRevenue: 'إيرادات الشهر الحالي',
    revenueMinusExpenses: 'الإيرادات بعد خصم المصروفات',
    pendingInvoices: 'فواتير معلقة',
    ordersPending: 'طلبات معلقة',
    expenseEntries: 'إدخالات المصروفات',
    availableCashFlow: 'التدفق النقدي المتاح',
    paymentsReceived: 'المدفوعات المستلمة',
    thisMonthPayments: 'مدفوعات هذا الشهر',
    inventoryValue: 'قيمة المخزون',
    costValue: 'قيمة التكلفة',
    selling: 'البيع',
    warehouses: 'مستودعات',
    newThisMonth: 'جديد هذا الشهر',
    fromLastMonth: 'من الشهر الماضي',
    todaySales: 'مبيعات اليوم',
    daily: 'يومي',
    monthSales: 'مبيعات الشهر',
    monthly: 'شهري',
    collectedTax: 'الضريبة المحصلة',
    vatCollectedFromSales: 'ضريبة القيمة المضافة المحصلة من المبيعات',
    salesOverview: 'نظرة عامة على المبيعات',
    salesDistribution: 'توزيع المبيعات',
    categoryPerformance: 'أداء الفئات',
    inventoryValueBreakdown: 'تفصيل قيمة المخزون',
    realTimeWarehouseAnalysis: 'تحليل المستودعات في الوقت الفعلي',
    loadingWarehouseBreakdown: 'جاري تحميل تفاصيل المستودعات',
    totalCostValue: 'إجمالي قيمة التكلفة',
    totalSellingValue: 'إجمالي قيمة البيع',
    totalQuantity: 'الكمية الإجمالية',
    units: 'وحدات',
    sellingValue: 'قيمة البيع',
    avgUnitCost: 'متوسط تكلفة الوحدة',
    
    // Login page
    signInToAccount: 'تسجيل الدخول إلى حسابك',
    welcomeBack: 'مرحبًا بعودتك',
    signInPrompt: 'تسجيل الدخول إلى نظام Premier ERP',
    email: 'البريد الإلكتروني',
    enterEmail: 'أدخل بريدك الإلكتروني',
    password: 'كلمة المرور',
    enterPassword: 'أدخل كلمة المرور',
    signIn: 'تسجيل الدخول',
    secureERPSystem: 'نظام Premier ERP الآمن',
    enterpriseSecurity: 'أمن المؤسسات',
    termsAndPrivacy: 'بتسجيل الدخول، فإنك توافق على شروط الخدمة وسياسة الخصوصية',
    
    // Customer Management
    customerRecords: 'سجلات العملاء',
    allCustomers: 'جميع العملاء',
    activeCustomers: 'العملاء النشطون',
    inactiveCustomers: 'العملاء غير النشطين',
    viewProfile: 'عرض الملف الشخصي',
    viewOrders: 'عرض الطلبات',
    editCustomer: 'تعديل العميل',
    deleteCustomer: 'حذف العميل',
    customerDeleted: 'تم حذف العميل بنجاح',
    importCustomers: 'استيراد العملاء',
    exportCustomers: 'تصدير العملاء',
    addCustomer: 'إضافة عميل',
    searchCustomers: 'البحث عن العملاء بالاسم أو البريد الإلكتروني أو الهاتف',
    filterByStatus: 'فلتر حسب الحالة',
    showingResults: 'عرض النتائج',
    noCustomersFound: 'لم يتم العثور على عملاء',
    tryDifferentSearch: 'حاول تعديل معايير البحث',
    loadingCustomers: 'جاري تحميل العملاء...',
    
    // Customer Analytics
    reportsAnalytics: 'التقارير والتحليلات',
    totalCustomers: 'إجمالي العملاء',
    active: 'نشط',
    newThisMonth: 'جدد هذا الشهر',
    avgOrderValue: 'متوسط قيمة الطلب',
    perCustomer: 'لكل عميل',
    repeatCustomers: 'العملاء المتكررون',
    retentionRate: 'معدل الاحتفاظ',
    customerDistributionBySector: 'توزيع العملاء حسب القطاع',
    topCustomersByRevenue: 'أفضل العملاء حسب الإيرادات',
    geographicDistribution: 'التوزيع الجغرافي',
    customers: 'عملاء',
    
    // Additional Customer Page translations
    customerManagement: 'إدارة العملاء',
    manageClients: 'إدارة العملاء',
    activeSectors: 'القطاعات النشطة',
    industryTypes: 'أنواع الصناعات',
    customerValue: 'قيمة العملاء',
    totalPortfolio: 'المحفظة الإجمالية',
    recentAdditions: 'الإضافات الأخيرة',
    topSector: 'القطاع الأعلى',
    geographicSpread: 'الانتشار الجغرافي',
    cities: 'مدن',
    coverageArea: 'منطقة التغطية',
    monthlyIncrease: 'الزيادة الشهرية',
    errorLoadingCustomers: 'خطأ في تحميل العملاء',
    pleaseTryAgainLater: 'يرجى المحاولة مرة أخرى لاحقاً',
    noMatchingCustomersFound: 'لم يتم العثور على عملاء مطابقين',
    tryAdjustingSearchQuery: 'حاول تعديل استعلام البحث',
    noCustomersAvailable: 'لا يوجد عملاء متاحون',
    action: 'الإجراء',
    customerReportsAnalytics: 'تقارير وتحليلات العملاء',
    comprehensiveReportsInsights: 'تقارير ورؤى شاملة',
    exportPDF: 'تصدير PDF',
    loadingReports: 'جاري تحميل التقارير...',
    customerRevenue: 'إيرادات العملاء',
    monthlyGrowthTrend: 'اتجاه النمو الشهري',
    activeAccounts: 'الحسابات النشطة',
    
    // Create Invoice page
    draftInvoices: 'مسودات الفواتير',
    createNewInvoice: 'إنشاء فاتورة جديدة',
    createInvoiceDescription: 'إنشاء فاتورة جديدة عن طريق اختيار عميل وإضافة منتجات',
    saveAsDraft: 'حفظ كمسودة',
    previewInvoice: 'معاينة الفاتورة',
    invoicesInProgress: 'الفواتير قيد العمل',
    resetToInvoice1: 'إعادة تعيين إلى الفاتورة 1',
    newInvoice: 'فاتورة جديدة',
    invoiceProgressAutoSaved: 'يتم حفظ تقدم الفاتورة تلقائيًا. يمكنك العمل على ما يصل إلى 4 فواتير في نفس الوقت.',
    nextInvoiceNumber: 'رقم الفاتورة التالي',
    customerInformation: 'معلومات العميل',
    selectOrCreateCustomer: 'اختر عميلاً موجودًا أو أنشئ عميلاً جديدًا',
    customer: 'العميل',
    selectCustomer: 'اختر عميل...',
    searchCustomer: 'البحث عن عميل...',
    noCustomersFoundFor: 'لم يتم العثور على عملاء لـ',
    createNewCustomer: 'إنشاء عميل جديد',
    typeToSearchCustomers: 'اكتب للبحث عن العملاء...',
    paperInvoiceNumber: 'رقم الفاتورة الورقية',
    paperInvoiceNumberPlaceholder: 'P-2025001',
    physicalInvoiceReference: 'رقم مرجع الفاتورة الفعلية لحفظ السجلات',
    approvalNumber: 'رقم الموافقة',
    approvalNumberPlaceholder: 'APP-2025001',
    internalApprovalReference: 'رقم مرجع الموافقة الداخلية',
    code: 'الكود',
    mobile: 'الجوال',
    etaNumber: 'رقم ETA',
    sector: 'القطاع',
    email: 'البريد الإلكتروني',
    address: 'العنوان',
    newCustomer: 'عميل جديد',
    companyName: 'اسم الشركة',
    companyNamePlaceholder: 'اسم الشركة',
    name: 'الاسم',
    customerNamePlaceholder: 'اسم العميل',
    position: 'المنصب',
    jobTitlePositionPlaceholder: 'المسمى الوظيفي/المنصب',
    phone: 'الهاتف',
    phoneNumberPlaceholder: 'رقم الهاتف',
    businessSectorPlaceholder: 'قطاع الأعمال',
    taxNumberEtaRegistration: 'الرقم الضريبي (تسجيل ETA)',
    egyptianTaxAuthorityPlaceholder: 'رقم تسجيل مصلحة الضرائب المصرية',
    requiredForEtaPortal: 'مطلوب لظهور الفواتير في بوابة ETA الخاصة بالعميل',
    customerEmailPlaceholder: 'customer@example.com',
    customerAddressPlaceholder: 'عنوان العميل',
    saveCustomer: 'حفظ العميل',
    invoiceItems: 'بنود الفاتورة',
    addProductsToInvoice: 'أضف منتجات إلى هذه الفاتورة'
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
    
    // Update document direction and lang attribute
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
  };

  const isRTL = language === 'ar';

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  useEffect(() => {
    // Set initial direction and lang
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language, isRTL]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, isRTL, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};